In [1]:
e = 1

while (1 + e != 1) :
    e = e / 2

print(e,"e is same as one now")

1.1102230246251565e-16 e is same as one now


1 + 1 , 2 + 1 , 3 + 2, 5 + 3

In [16]:
a = 1
b = 1
i = 0
max_range_s = input("Value of max fibonnaci sequence")
max_range = int (max_range_s)
while i < max_range :
    tmp_val = b
    b = a + b
    a = tmp_val
    i = i + 1
    print(a)

1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


In [59]:
n_s = input("Value of n")
n = int(n_s)

L = list(range(n + 1))
L[1] = 0
p = 2
while (p **2 <= n) :
    for i in range(p**2, n + 1, p):
        # print(L[i])
        L[i] = 0
    q = p + 1
    for i in range(len(L)):
        if (L[i] != 0 and L[i] > p):
            q = L[i]
            # print(q)
            break
    p = q
for i in range(len(L)):
    if (L[i] != 0) :
        print(i)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [65]:
# Re-performing the calculation for the dilated half-life and the distance covered for part (b)
import math
half_life_muon = 3 * 10 **-6
speed_of_light = 3 * 10 ** 8
# Recalculating the dilated half-life using the time dilation formula
dilated_half_life_b_recalc = half_life_muon / math.sqrt(1 - (0.9994 * speed_of_light)**2 / speed_of_light**2)

# Recalculating the distance traveled by muons in their dilated half-life
distance_dilated_half_life_b_recalc = 0.9994 * speed_of_light * dilated_half_life_b_recalc


rev = distance_dilated_half_life_b_recalc/ ( 3.14 * 15)
dilated_half_life_b_recalc, distance_dilated_half_life_b_recalc
# rev

(8.661553368306921e-05, 25969.069308857812)

In [73]:
# Constants for part (c)
muon_speed_c = 0.9999 * speed_of_light  # Speed of muon
height_above_earth = 20e3  # Height above Earth's surface in meters

# Time dilation for the new speed
dilated_half_life_c = half_life_muon / math.sqrt(1 - muon_speed_c**2 / speed_of_light**2)

# Time taken for the muon to travel 20 km in the Earth frame
time_to_earth = height_above_earth / muon_speed_c

# Probability of survival in the Earth frame
# Using the formula P(τ) = 2^(-τ/T1/2), where τ is the time in the Earth frame
probability_survival_earth_frame = 2**(-time_to_earth / dilated_half_life_c)

# Length contraction in the muon's frame
contracted_length = height_above_earth * math.sqrt(1 - muon_speed_c**2 / speed_of_light**2)

# Time taken to travel the contracted distance in the muon's frame
time_in_muon_frame = contracted_length / muon_speed_c

# Probability of survival in the muon's frame
probability_survival_muon_frame = 2**(-time_in_muon_frame / half_life_muon)

probability_survival_earth_frame, probability_survival_muon_frame
# dilated_half_life_c
# time_to_earth

(0.8042448774813745, 0.8042448774813745)

In [76]:
# Time taken for the muon to travel 20 km without relativistic effects
time_to_earth_non_relativistic = height_above_earth / muon_speed_c

# Probability of survival without relativistic effects
probability_survival_non_relativistic = 2**(-time_to_earth_non_relativistic / half_life_muon)
probability_survival_non_relativistic
# time_to_earth_non_relativistic

2.040682867333229e-07

In [82]:
a = ['h', 'g']
b = 'hi'

a.append(b) 
c = a + [b]
# a += b
print(a==c)
a, c

False


(['h', 'g', 'hi'], ['h', 'g', 'hi', 'hi'])

In [87]:
John = 'cs'
Tim = John
Tim += ', math'
Anna = ['electrical']
Julie = Anna
Julie += ['physics']
print(John, Anna)

cs ['electrical', 'physics']


In [88]:
a = [0,1,2,3,4,5,6,7,8,9]
a[1::2][::-1]

[9, 7, 5, 3, 1]

In [99]:
# def a_m(p) :
#     p.append('m')
def s_m(p):
    # print("p", p)
    # p = ['p']
    # print("p", p)
    p.append('ec')
    print("p", p)
John = ['cs']
# T = John
# a_m(T)
s_m(John)
print(John)

p ['cs', 'ec']
['cs', 'ec']


In [106]:
class test:
    def __init__(self) -> None:
        self.variable = 'Old'
        self.variable = self.Change(self.variable)
    def Change(self, var):
        var = 'New'
        return var
obj = test()
print(obj.variable)

New


In [110]:
a = [3]
b = [5]
def do_s(a,b) :
    a += [1]
    b +=[2] 
do_s(a,b)
a,b

([3, 1], [5, 2])

In [142]:
import numpy as np
a = np.array([[1,4,9],[2,8,18]])
# a = np.zeros(np.arange(12).reshape(4,3))
# a = np.zeros((4,3))
# print(a.reshape(6,1))
b = np.arange(20).reshape(5,4)
a = np.arange(20).reshape(5,4)
print(b.shape)
print(b)
print(a)
c = a + b
print(c.shape)
print(c)

(5, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]]


In [154]:
x = 37 % 4 * (3 + 2) * 4 + 2
x = 1 - 0.18
x = 0.60/x
y = x
x is y

True

In [159]:
A = [1,2,3,3.7]
B = np.array([1.2,2,6.1,8])

# type(A[3])
type(B[1])

numpy.float64

In [160]:
y = 2**20 * 26
y

27262976